### ISSUE TITLE
Folder structure in zip file incorrect

### ISSUE THREAD

**Issue by kenpoh01** [nlx3647/dataset#1]
I wasn't able to get the Data Editor to import the zip file as is.  I had to find the lowest folder in the hierarchy in the zip file called "DataSet_Full DataSet" and zip that folder into it's own zip file, which I called SWDataSet.zip (Not sure if that naming convention matters).  Then the data editor was able to import it.

**Comment by nlx3647** [comment]
The tool by default requires SWDataSet.zip as the last part of the name, so that piece is by design (done by Oggdude, not by me).

As far as the way the zip is downloaded, that's correct as well, and it looks like Git zips up the branch with the format "repository - branch .zip".

Neither one is a whole lot I can do about, I'm afraid.

NLX
